### ISSUE TITLE
Validate command before executing

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/cron-command#3]
While executing cron commands, If the command would contain `;` or `#`, then everything that comes after it will be ignored(till end of line) since ofelia uses INI style config in which both of them are treated as comments(and hence everything that follows it is ignored)

i.e. In a job like this:

```
[job-exec "abc.test-touch__tmp_a-Jdhbn"]
schedule = * * * * *
container = abctest_php_1
command = touch /tmp/a.txt ; touch /tmp/b.txt
```

`touch /tmp/b.txt` will never be called.

**Comment by rahul286** [comment]
@kirtangajjar can we use quotes or escaping.

Like  `"touch /tmp/a.txt ; touch /tmp/b.txt"`
or ` touch /tmp/a.txt \; touch /tmp/b.txt`

**Comment by kirtangajjar** [comment]
@rahul286 Nope. That doesn't work :(

**Comment by mbtamuli** [comment]
Validation has been taken care of in https://github.com/EasyEngine/cron-command/pull/9.

As for allowing the syntax, it is being tracked in https://github.com/EasyEngine/cron-command/issues/10
