### ISSUE TITLE
Commands with ; and # should be able to execute

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/cron-command#4]
Currently we can't accept commands which have `;` or `#` since our cron scheduler [ofelia](https://github.com/mcuadros/ofelia/) uses INI sytle config in which everything after `;` or `#` is considered comment.

[We have placed validation on it](https://github.com/EasyEngine/cron-command/issues/3). But such commands are expected to work out of box and hence we must find a workaround

**Comment by rahul286** [comment]
@kirtangajjar can we use quotes or escaping?

Like  `"touch /tmp/a.txt ; touch /tmp/b.txt"`
or ` touch /tmp/a.txt \; touch /tmp/b.txt`

**Comment by kirtangajjar** [comment]
It didn't work with single quote. Let me try with double quote and check

**Comment by mbtamuli** [comment]
I will take a look at [ofelia](https://github.com/mcuadros/ofelia)'s code and try to see if we can make some modifications to be able to read the acceptable shell commands.

**Comment by mbtamuli** [comment]
This is being tracked in #10
