### ISSUE TITLE
error ee cron list --all

### ISSUE THREAD

**Issue by gokuale** [EasyEngine/cron-command#52]
Hello,
i have upgrade to last version and i have this error:

ee cron list --all:
Error: Invalid field: user.

i have 1 default cron for one site install and 3 cron for host
thanks a lot

**Comment by kirtangajjar** [comment]
@gokuale Thanks for reporting this issue! Can you please tell us the output of:
```
sqlite3 /opt/easyengine/db/ee.sqlite -cmd ".schema cron"
sqlite3 /opt/easyengine/db/ee.sqlite -cmd "select * from cron"
```

**Comment by gokuale** [comment]
hello
this is output

sqlite3 /opt/easyengine/db/ee.sqlite -cmd ".schema cron"
CREATE TABLE cron (
                        id INTEGER,
                        site_url VARCHAR NOT NULL,
                        user VARCHAR,
                        command VARCHAR NOT NULL,
                        schedule VARCHAR NOT NULL,
                        PRIMARY KEY (id)
                );
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite>

sqlite3 /opt/easyengine/db/ee.sqlite -cmd "select * from cron"
1|www.example.com|www-data|sh -c 'wp cron event run --due-now'|0 1/10 * * * *
2|host|www-data|sh -c 'ee site ssl-renew --all'|@weekly
3|host||sh -c 'ee cli update'|@weekly

**Comment by gokuale** [comment]
> hello
> this is output
> 
> sqlite3 /opt/easyengine/db/ee.sqlite -cmd ".schema cron"
> CREATE TABLE cron (
> id INTEGER,
> site_url VARCHAR NOT NULL,
> user VARCHAR,
> command VARCHAR NOT NULL,
> schedule VARCHAR NOT NULL,
> PRIMARY KEY (id)
> );
> SQLite version 3.22.0 2018-01-22 18:45:57
> Enter ".help" for usage hints.
> sqlite>
> 
> sqlite3 /opt/easyengine/db/ee.sqlite -cmd "select * from cron"
> 1|www.example.com|www-data|sh -c 'wp cron event run --due-now'|0 1/10 * * * *
> 2|host|www-data|sh -c 'ee site ssl-renew --all'|@Weekly
> 3|host||sh -c 'ee cli update'|@Weekly

Thanks i resolve update table cron and set user www-data because in last row it's blank, i don't think why it's blank but now it's ok
thanks a lot
